Improve Loading page design for modern themes
OpenSilver/OpenSilver.VSIX pull request #14
Opened 2024-12-09 08:39 UTC by ousspero

2024-12-10 07:06 UTC, jacob-l requested changes

2024-12-10 07:06 UTC, jacob-l commented on src/OpenSilver.TemplateWizards/Assets/Themes/Common/index.html
We can not use this index html, because it includes meta for xaml.io.

2024-12-10 07:06 UTC, jacob-l commented on src/OpenSilver.TemplateWizards/AppCustomizationWizard.cs
> +                ;
Not necessary

2024-12-10 07:06 UTC, jacob-l commented on src/OpenSilver.TemplateWizards/AppCustomizationWizard.cs
> +
Extra lines can be removed

2024-12-10 07:32 UTC, ousspero commented on src/OpenSilver.TemplateWizards/Assets/Themes/Common/index.html
I'll compare with the previous one

2024-12-11 06:25 UTC, jacob-l commented
I copied some styles and implemented in another commit - https://github.com/OpenSilver/OpenSilver.VSIX/commit/0583f6484342be037ae661c4e2490e6db0f53e14

2024-12-11 06:25 UTC, closed without merging